import Link from "next/link";
import { PageLabel } from "./PageLabel";

const POLICY: { id: string; title: string; body: string[] }[] = [
  {
    id: "accuracy",
    title: "Accuracy",
    body: [
      "We check facts before we publish. Names, titles, dates, numbers and quotes are confirmed with the source or a record. If we cannot confirm something, it does not run.",
    ],
  },
  {
    id: "fairness",
    title: "Fairness",
    body: [
      "Anyone who is criticised in a news story gets a real chance to respond before it runs. We quote people in context and do not bend their words to fit a story.",
    ],
  },
  {
    id: "corrections",
    title: "Corrections",
    body: [
      "When we get something wrong, we fix it and say so. A correction note with the date is added to the end of the story. We do not quietly delete or rewrite published work.",
      "To report an error, use the contact form or message an editor.",
    ],
  },
  {
    id: "sourcing",
    title: "Sourcing",
    body: [
      "We tell readers where information comes from. We prefer named, on-the-record sources, talk to more than one person on contested topics, and credit other publications when we use their reporting. Photos and art are credited to the person who made them.",
    ],
  },
  {
    id: "anonymity",
    title: "Anonymous sources",
    body: [
      "We rarely publish without a name. An Editor-in-Chief must approve any anonymous source, and only when the person could face real harm for speaking and the information matters to readers. The editors always know who the source is, even when readers do not.",
    ],
  },
  {
    id: "conflicts",
    title: "Conflicts of interest",
    body: [
      "Staff do not cover a team, club or event they belong to, or people they are close to, without telling an editor first. Where a connection matters, we either assign someone else or say so in the story.",
    ],
  },
  {
    id: "ai",
    title: "Use of AI",
    body: [
      "Stories, photos and art on this site are made by students. We do not publish text or images generated by AI tools. Writers may use tools for spelling and grammar, but every fact is checked by a person and every published word is the writer's own.",
    ],
  },
  {
    id: "opinion",
    title: "Opinion and news",
    body: [
      "News stories report what happened without the writer's own view. Opinion pieces, reviews and columns are labelled and run in the Opinion section or are clearly marked. They speak for their writers, not for the Press or for AISR.",
    ],
  },
];

// The Press's editorial standards, shown on the About page.
export function EthicsPolicy() {
  return (
    <section id="ethics" aria-labelledby="ethics-h" className="scroll-mt-28 border-t border-ink bg-cream">
      <div className="mx-auto grid max-w-page gap-12 px-4 py-20 sm:px-6 md:py-28 lg:grid-cols-12 lg:px-10">
        <div className="lg:col-span-4">
          <div className="lg:sticky lg:top-32">
            <PageLabel>Standards</PageLabel>
            <h2
              id="ethics-h"
              data-split="lines"
              className="mt-4 font-serif text-[clamp(2.5rem,4.6vw,4rem)] leading-[0.98] font-medium tracking-[-0.03em]"
            >
              Editorial policy
            </h2>
            <p className="mt-6 max-w-[40ch] font-serif text-lg leading-relaxed text-ink-soft">
              The rules every story on this site is held to. If you think we broke one,{" "}
              <Link href="/submit?kind=contact" className="text-ink underline decoration-gold decoration-2 underline-offset-4 hover:text-navy">
                tell us
              </Link>
              .
            </p>
          </div>
        </div>
        <ol className="grid gap-x-12 md:grid-cols-2 lg:col-span-8">
          {POLICY.map((item, i) => (
            <li key={item.id} id={item.id} data-card className="scroll-mt-28 border-t border-rule py-8">
              <h3 className="flex items-baseline gap-3 font-serif text-2xl leading-tight tracking-[-0.01em]">
                <span className="font-sans text-xs font-semibold text-gold tabular-nums">{String(i + 1).padStart(2, "0")}</span>
                {item.title}
              </h3>
              {item.body.map((para) => (
                <p key={para.slice(0, 24)} className="mt-3 font-serif text-[1.0625rem] leading-[1.65] text-ink/85">
                  {para}
                </p>
              ))}
            </li>
          ))}
        </ol>
      </div>
    </section>
  );
}
